# Generated by Django 3.1.6 on 2021-02-16 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.IntegerField(blank=True, null=True)),
                ('flow_run_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('call_type', models.CharField(choices=[('IC', 'inbound-call'), ('OC', 'outbound-call'), ('IM', 'inbound-missedcall'), ('OL', 'outbound-live-call')], max_length=50)),
                ('scheduled_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user_phone_number', models.CharField(max_length=50)),
                ('system_phone_number', models.CharField(max_length=50)),
                ('circle', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('NR', 'no-response'), ('U', 'unreachable'), ('DND', 'dnd'), ('IN', 'invalid-number'), ('R', 'rejected'), ('B', 'busy'), ('A', 'answered')], max_length=50)),
                ('listen_seconds', models.CharField(blank=True, max_length=50, null=True)),
                ('recording_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('dial_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'call_log',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('duration', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='ModuleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_optional', models.BooleanField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.content')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.module')),
            ],
            options={
                'db_table': 'module_content',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'partner',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('discontinuation_date', models.DateField(blank=True, null=True)),
                ('program_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='ProgramModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.module')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.program')),
            ],
            options={
                'db_table': 'program_module',
            },
        ),
        migrations.CreateModel(
            name='SystemPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_phone',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address_line_1', models.TextField(blank=True, null=True)),
                ('address_line_2', models.TextField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admindashboard.partner')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_time_slot', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.user')),
            ],
            options={
                'db_table': 'user_program',
            },
        ),
        migrations.CreateModel(
            name='UserModuleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'pending'), ('I', 'in-progress'), ('C', 'complete')], default='P', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('module_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.modulecontent')),
                ('program_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.programmodule')),
                ('user_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.userprogram')),
            ],
            options={
                'db_table': 'user_module_content',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(max_length=50)),
                ('system_phone', models.CharField(max_length=50)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_type', models.CharField(choices=[('F', 'father'), ('M', 'mother'), ('GF', 'grandfather'), ('GM', 'grandmother'), ('O', 'other')], max_length=50)),
                ('area_type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_child_between_0_3', models.BooleanField(blank=True, null=True)),
                ('is_child_between_3_6', models.BooleanField(blank=True, null=True)),
                ('is_child_above_6', models.BooleanField(blank=True, null=True)),
                ('has_no_child', models.BooleanField(blank=True, null=True)),
                ('has_smartphone', models.BooleanField(blank=True, null=True)),
                ('has_dropped_missedcall', models.BooleanField(blank=True, null=True)),
                ('has_received_callback', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'pending'), ('I', 'in-progress'), ('C', 'complete')], default='P', max_length=50)),
                ('signup_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admindashboard.partner')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admindashboard.program')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admindashboard.user')),
            ],
            options={
                'db_table': 'registration',
            },
        ),
        migrations.CreateModel(
            name='PartnerSystemPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.partner')),
                ('system_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.systemphone')),
            ],
            options={
                'db_table': 'partner_system_phone',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admindashboard.program'),
        ),
        migrations.CreateModel(
            name='IvrPromptResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prompt_question', models.CharField(blank=True, max_length=1000, null=True)),
                ('response', models.CharField(blank=True, max_length=255, null=True)),
                ('user_phone', models.CharField(max_length=50)),
                ('is_call_log_processed', models.BooleanField(blank=True, null=True)),
                ('call_sid', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admindashboard.calllog')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admindashboard.content')),
            ],
            options={
                'db_table': 'ivr_prompt_response',
            },
        ),
        migrations.CreateModel(
            name='IvrPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prompt_question', models.CharField(blank=True, max_length=1000, null=True)),
                ('possible_response', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('A', 'active'), ('I', 'inactive')], default='A', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admindashboard.content')),
            ],
            options={
                'db_table': 'ivr_prompt',
            },
        ),
        migrations.AddField(
            model_name='calllog',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admindashboard.registration'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admindashboard.user'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='user_module_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admindashboard.usermodulecontent'),
        ),
        migrations.CreateModel(
            name='CallbackTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('missed_call_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admindashboard_callbacktracker_related', related_query_name='admindashboard_callbacktrackers', to='admindashboard.calllog')),
                ('response_call_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.calllog')),
            ],
            options={
                'db_table': 'callback_tracker',
            },
        ),
    ]
